<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroicons */
$heroSolidicons = $viewModels->require(HeroiconsSolid::class);
$heroOutlineIcons = $viewModels->require(HeroiconsOutline::class);
?>
<script>
    function initPopup() {
        return {
            isLoading: false,
            cookieName: 'suspend_bussiness_popup',
            isOpen: false,
            openPopup() {
                this.isLoading = true;
            },
            closePopup() {
                this.setCookie(365);
                this.isOpen = false;

            },
            setCookie(days = 1) {
                let d = new Date();
                d.setTime(d.getTime() + (days * 24 * 60 * 60 * 1000));
                let expires = "expires="+d.toUTCString();
                document.cookie = this.cookieName + "=true;" + expires + ";path=/";
            },
            getCookie() {
                var match = document.cookie.match(new RegExp('(^| )' + this.cookieName + '=([^;]+)'));
                if (match) {
                    return match[2];   
                }
            },
            checkCookie() {
                return this.isOpen = (this.getCookie() !== "true");
            }
        };
    }
</script>
<div x-data="initPopup()" x-init="checkCookie()">
    <div tabindex="-1" aria-modal="true" role="dialog" :class="{ 'hidden': !isOpen, 'fixed': isOpen }" class="overflow-y-auto overflow-x-hidden top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full justify-center items-center flex">
        <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
            <div class="modal-container relative flex justify-center" x-show="isOpen" @click.away="closePopup();" x-cloak>
                <div class="flex relative justify-between p-4 dark:border-gray-600">
                    <div class="modal-head absolute right-4 order-2">
                        <div class="close" @click="closePopup();">
                            <?= $heroOutlineIcons->xCircleHtml('w-8 h-8 bg-white rounded-full') ?>
                        </div>
                    </div>

                    <div class="modal-body">
                        <img class="md:hidden" src="/media/wysiwyg/stop.png"/>
                        <img class="hidden md:block" src="/media/wysiwyg/suspendpopup/suspend-20230113-131920.jpg"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div x-show="isOpen" x-cloak class="w-full h-full z-40 modal-backdrop opacity-50 bg-black fixed top-0 right-0 left-0 md:index-0"></div>
</div>
