<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header\Logo;
use Hyva\Theme\ViewModel\Logo\LogoSizeResolver;

/** @var Logo $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var LogoSizeResolver $logoSizeResolver */

$storeName = $block->getThemeName() ?: $block->getLogoAlt();

$logoSizeResolver = $viewModels->require(LogoSizeResolver::class);
$logoWidth = $logoSizeResolver && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();

/** @var \Hyva\Theme\ViewModel\Logo\LogoPathResolver $logoPathResolver */
$logoPathResolver = $block->getData('logoPathResolver');
$logoSrc = $logoPathResolver && method_exists($logoPathResolver, 'getLogoSrc')
    ? $logoPathResolver->getLogoSrc($block->getData('logo_file'))
    : $block->getLogoSrc();
?>
<div class="md:w-auto flex-none">
    <a href="<?= $escaper->escapeUrl($block->getUrl('')) ?>"
       title="<?= $escaper->escapeHtmlAttr($storeName) ?>"
       aria-label="store logo">
        <img class="block max-w-full h-auto leading-6 text-orange-500 border-0 cursor-pointer
box-border" src="<?= $escaper->escapeUrl($logoSrc) ?>"
             title="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
             alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $logoWidth ?
                'width="' . $escaper->escapeHtmlAttr($logoWidth) . '"' :
                'width="200"' ?>
            <?= $logoHeight ?
                'height="' . $escaper->escapeHtmlAttr($logoHeight) . '"' :
                'height="150"' ?>
        />
        <?= $escaper->escapeHtml($storeName) ?>
    </a>
</div>
