<div
    class="relative w-full bg-container-lighter border-container-lighter mx-auto md:mx-auto md:px-10 leading-6"
    style='background-color: #1c1a1b'
>
    <div class="md:container md:mx-auto">
        <div
            class="grid grid-cols-2 gap-4 text-white"
            style="z-index: 1;"
        >
            <div class="flex flex-wrap justify-start ml-6 md:ml-0 items-center">
                <a href="mailto:info@disenparts.com">
                    <p class="py-1 px-0 my-0 box-border">
                        info@disenparts.com
                    </p>
                </a>
            </div>
            <div class="flex flex-wrap justify-end">
                <div class="py-1 px-0 box-border">
                    <div class="box-border">
                        <div
                            class="inline-block py-0 pr-2 pl-0 mr-0"
                            data-ui-id="language-switcher"
                            id="switcher-language"
                        >
                            <!--Switch Store-->
                            <div class="md:flex items-center order-3 md:pl-8 md:pl-0">
                                <?= $block->getChildHtml('store-language-switcher') ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>