<div class="my-8 py-8 border-t-2 border-gray-300" id="external-script">

</div>
<script>
    (function () {
        const script = document.createElement('script')
        script.src = 'https://cdn.verifypass.com/seller/embed/load.js';
        script.id = 'vfyps_widget';
        script.setAttribute('data-key', '31dc9cd3f');
        script.setAttribute('data-show-all', true);
        document.getElementById('external-script').append(script);
    })();
</script>