<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Customer $customer */
$customer = $viewModels->require(Customer::class);
/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
?>
<!--<div class="md:w-1/2 w-full flex flex-wrap pr-4">-->
<div class="w-full flex flex-wrap pr-5 py-8">
    <!--    <div class="w-full grid grid-cols-1 sm:grid-cols-2 gap-8 xl:col-span-2">-->
    <div class="pr-8 pb-4 lg:w-1/3 md:w-1/2 text-white">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_column_shop')->toHtml(); ?>
    </div>
    <div class="pr-4 pb-4 lg:w-1/3 md:w-1/2 md:flex pt-4">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_column_links')->toHtml(); ?>
    </div>
    <!-- <div class="pr-4 pb-4 lg:w-1/8 md:w-1/2">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_support')->toHtml(); ?>
    </div> -->
    <div class="pr-4 pb-4 lg:w-1/3 md:w-1/2 pt-4">
        <?php if ($childrenHtml = $block->getChildHtml()): ?>
            <?= /** @noEscape */ $childrenHtml ?>
        <?php endif; ?>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_accepted_card_hyva')->toHtml(); ?>
    </div>
</div>
