<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Cms\Block\Block as CmsBlock;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<div x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
     class="z-20 order-2 sm:order-1 lg:order-2 navigation hidden lg:flex"
>
    <!-- desktop -->
    <div @load.window="setActiveMenu($el)"
         class="justify-between items-center mx-auto w-full max-w-7xl"
    >
        <nav
            class="w-full flex justify-start w-auto min-h-0"
        >
            <?php foreach ($menuItems as $index => $itemLevel1): ?>
                <?php $singleItems = []; ?>
                <div class="level-0 flex items-center p-1 mx-1 border-b-2 border-transparent transition transition-colors duration-500 group xl:p-2 xl:mx-2 hover:border-primary focus-within:border-primary"
                     @mouseover.stop="hoverTopPosition = $event.currentTarget.offsetTop + $event.currentTarget.getBoundingClientRect().height"
                >
                    <span class="items-center block text-md">
                    <a href="<?= $escaper->escapeUrl($itemLevel1['url']) ?>"
                       @focus="hoverTopPosition = $event.currentTarget.parentNode.offsetTop + $event.currentTarget.parentNode.getBoundingClientRect().height"
                       title="<?= $escaper->escapeHtmlAttr($itemLevel1['name']) ?>"
                       class="w-full block text-xl text-gray-700 font-extrabold px-4 py-3 hover:bg-gray-light">
                        <span><?= $escaper->escapeHtml($itemLevel1['name']) ?></span>
                        <?php if (!empty($itemLevel1['childData'])): ?>
                            <span class="inline items-center">
                                <?= $heroiconsSolid->chevronDownHtml('h-2 w-3 hidden lg:inline-block ml-1', 24, 24) ?>
                            </span>
                        <?php endif; ?>
                    </a>
                        </span>
                    <?php if (!empty($itemLevel1['childData'])): ?>
                        <div class="absolute left-0 top-full z-10 -mt-3 w-full bg-white opacity-0 transition-opacity ease-out pointer-events-none group-hover:opacity-100 focus-within:opacity-100 group-hover:pointer-events-auto"
                             :style="`margin-top: 0; top: ${hoverTopPosition}px;`"
                        >
                            <div class="bg-gray-lightest px-6 py-4">
                                <div class="container">
                                <?php
                                $catIdLvl1    = ($pos = strrpos($itemLevel1['id'], '-')) !== false
                                    ? substr($itemLevel1['id'], $pos + 1)
                                    : 0;
                                $cmsBlockHtml = $catIdLvl1
                                    ? $this->getLayout()
                                        ->createBlock(CmsBlock::class)
                                        ->setBlockId('megamenu_block_left_cat' . $catIdLvl1)
                                        ->toHtml()
                                    : '';

                                if (! empty($cmsBlockHtml)): ?>
                                    <div class="max-w-xs 2xl:block">
                                        <?= /** @noEscape */ $cmsBlockHtml ?>
                                    </div>
                                <?php endif; ?>
                                <div class="mx-auto">
                                    <ul class="grid grid-cols-4 gap-4">
                                        <?php foreach ($itemLevel1['childData'] as $itemLevel2): ?>
                                            <?php if (empty($itemLevel2['childData'])): ?>
                                                <?php $singleItems[] = $itemLevel2 ?>
                                                <?php continue; ?>
                                            <?php endif; ?>
                                            <li class="level-1 min-w-48">
                                                <a href="<?= $escaper->escapeUrl($itemLevel2['url']) ?>"
                                                   title="<?= $escaper->escapeHtmlAttr($itemLevel2['name']) ?>"
                                                   class="level-1 p-1 block text-base font-semibold leading-loose hover:underline">
                                                    <?= $escaper->escapeHtml($itemLevel2['name']) ?>
                                                </a>

                                                <ul class="z-10 w-full">
                                                    <?php foreach ($itemLevel2['childData'] as $itemLevel3): ?>
                                                        <li class="level-2">
                                                            <a href="<?= $escaper->escapeUrl($itemLevel3['url']) ?>"
                                                               title="<?= $escaper->escapeHtmlAttr($itemLevel3['name']) ?>"
                                                               class="level-2 p-1 block text-lg md:text-sm hover:underline"><?= $escaper->escapeHtml($itemLevel3['name']) ?></a>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>

                                            </li>
                                        <?php endforeach; ?>
                                        <?php if ($singleItems): ?>
                                        <li class="level-1 min-w-48">
                                            <?php foreach ($singleItems as $item): ?>
                                                <a href="<?= $escaper->escapeUrl($item['url']) ?>"
                                                   title="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                                                   class="level-1 p-1 block text-base font-semibold leading-loose hover:underline">
                                                    <?= $escaper->escapeHtml($item['name']) ?>
                                                </a>
                                            <?php endforeach; ?>
                                            <?php endif; ?>
                                    </ul>
                                </div>
                                </div>
                                <?php
                                $cmsBlockHtml = $catIdLvl1
                                    ? $this->getLayout()
                                        ->createBlock(CmsBlock::class)
                                        ->setBlockId('megamenu_block_right_cat' . $catIdLvl1)
                                        ->toHtml()
                                    : '';

                                if (! empty($cmsBlockHtml)): ?>
                                    <div class="max-w-xs 2xl:block">
                                        <?= /** @noEscape */ $cmsBlockHtml ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>

        </nav>
    </div>

</div>
<script>
    'use strict';

    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            hoverTopPosition: '100%',
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    // if (!item.classList.contains('level-0')) {
                    //     item.classList.add('underline');
                    // }
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').classList.add('border-secondary');
                });
            }
        }
    }
</script>
