<?php

/**
 * Mirasvit - Search Autocomplete Compatability Module
 *
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/** @var Escaper $escaper */
/** @var Template $block */
/** @var SearchHelper $helper */
/** @var \Mirasvit\SearchAutocomplete\Block\Injection $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data as SearchHelper;
use Mirasvit\SearchAutocomplete\Model\ConfigProvider;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */


$config = $block->getJsConfig();

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

$helper = $this->helper(SearchHelper::class);
$col2 = $config['layout'] == "2columns";

?>

<?php /** Main Search Area */ ?>
<div class="relative justify-center md:justify-start" x-data="initMirasvitSearch()" @click.away="closeSearch">
    <form class="form minisearch flex justify-center md:justify-start pt-4 md:pt-0" id="search_mini_form" action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get" autocomplete="off">
        <label class="hidden" for="search" data-role="minisearch-label">
            <span><?= $escaper->escapeHtml(__('Search')) ?></span>
        </label>
        <input id="search" x-ref="searchInput" type="search" name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>" value="<?= $escaper->escapeHtmlAttr($helper->getEscapedQueryText()) ?>" placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your part number')) ?>" maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>" class="inline-flex w-full md:h-full h-1/2" x-on:keyup.debounce.300="doSearch($refs.searchInput.value)" x-on:click.debounce.150="openSearch" x-on:keydown.debounce.100="startSearch($refs.searchInput.value)" />
        <!--Search Icon-->
        <button id="menu-search-icon"
                class="rounded-none action primary inline-flex flex-shrink-0 ml-auto xl:mt-0 btn btn-primary"
        >
                <span class="sr-only label">
                    <?= $escaper->escapeHtml(__('Search')) ?>
                </span>

            <?= $heroicons->searchHtml(
                "w-8 h-4 md:h-4 md:w-6",
                25,
                25
            ) ?>
        </button>
    </form>


    <div x-cloak x-show="isOpen" id="mirasvitSearchResults" class="block overflow-hidden absolute mt-2 max-w-screen-md leading-6 text-left
bg-white rounded-sm border-t-2 border-solid md:block w-full box-border z-30 shadow-md
border-sky-500 text-stone-500">
        <?php /** Loading Spinner */ ?>
        <?= $block->getChildHtml('loading.search');  ?>
        <template x-if="hotSearch">
            <div class="m-3">
                <p class="text-lg leading-normal transition appearance-none text-grey-800 lg:text-xl"><?= $escaper->escapeHtml(__('Hot Searches: ')) ?></p>
                <div class="my-3 flex flex-wrap">
                    <?php if ($config['popularSearches']) : ?>
                        <?php foreach ($config['popularSearches'] as $search) :  ?>
                            <span x-on:click="hotSearchClickEvent" class="m-1 bg-gray-200 hover:bg-gray-300 rounded-full px-2 font-bold text-sm leading-loose cursor-pointer"><?= $escaper->escapeHtml(__($search)) ?></span>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </template>
        <template x-if="searchResults">
            <div class="m-3 <?= $col2 ? 'grid gap-4 lg:grid-cols-12' : '' ?>">
                <?php if ($col2) : ?>
                <div class="col-span-12 lg:col-span-8 lg:order-1">
                    <?php endif; ?>
                    <p class="text-lg leading-normal transition appearance-none text-grey-800 lg:text-xl"><?= $escaper->escapeHtml(__('Products: ')) ?>
                        <template x-if="searchItems != ''">
                            <span class="text-gray-500" x-html="searchItemsTotal  + ' <?= $escaper->escapeHtml(__('Items')) ?>'"></span>
                        </template>
                    </p>
                    <div class="container mx-auto grid xs:grid-cols-1 mb-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 p-2 md:pt-6 gap-4">
                        <template x-for="item in searchItems">
                            <div class="flex transform transition duration-500 hover:scale-105 flex-wrap md:max-w-md bg-white shadow-lg rounded-lg overflow-hidden flex-col lg:flex-row xl:flex-nowrap">
                                <a x-bind:href="`${item.url}`" class="w-full flex flex-wrap flex-col">
                                    <div class="w-full">
                                        <img x-bind:src="`${item.image}`" class="mx-auto" />
                                    </div>
                                    <div class="w-full p-4">
                                        <h4 class="text-gray-900 font-bold text-base lg:text-lg" x-html="item.name"></h4>
                                        <p class="mt-2 text-gray-600 text-xs truncate" x-html="item.description"></p>
                                        <div class="flex item-center mt-2">
                                            <div x-html="item.rating"></div>
                                        </div>
                                        <div class="flex item-center justify-between mt-3 lg:flex-col xl:flex-row">
                                            <span class="text-gray-700 font-medium text-base" x-html="item.price"></span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </template>
                        <template x-if="searchItems == ''">
                            <p><?= $escaper->escapeHtml(__('No results found.')) ?></p>
                        </template>
                    </div>
                    <?php if ($col2) : ?>
                </div>
                <div class="col-span-12 lg:col-span-4">
                    <?php endif; ?>
                    <div class="mb-6">
                        <p class="text-lg mb-2 leading-normal transition appearance-none text-grey-800 lg:text-xl"><?= $escaper->escapeHtml(__('Categories: ')) ?><span class="text-gray-500" x-html="searchCategoriesTotal + ' Items'"></span></p>
                        <template x-for="category in searchCategories">
                            <div class="">
                                <a x-bind:href="`${category.url}`">
                                    <div class="my-3 flex flex-wrap">
                                        <span class="m-1 bg-gray-200 hover:bg-gray-300 rounded-full px-2 font-bold text-sm leading-loose cursor-pointer" x-html="category.name"></span>
                                    </div>
                                </a>
                                
                            </div>
                        </template>
                        <template x-if="searchCategories == ''">
                            <p><?= $escaper->escapeHtml(__('No results found.')) ?></p>
                        </template>
                    </div>

                    <div class="mb-6">
                        <p class="text-lg mb-2 leading-normal transition appearance-none text-grey-800 lg:text-xl"><?= $escaper->escapeHtml(__('CMS Pages: ')) ?><span class="text-gray-500" x-html="searchPagesTotal  + ' Items'"></span></p>
                        <template x-for="page in searchPages">
                            <div class="">
                                <a x-bind:href="`${page.url}`">
                                    <div class="my-3 flex flex-wrap">
                                        <span class="m-1 bg-gray-200 hover:bg-gray-300 rounded-full px-2 font-bold text-sm leading-loose cursor-pointer" x-html="page.name"></span>
                                    </div>
                                </a>
                            </div>
                        </template>
                        <template x-if="searchPages == ''">
                            <p><?= $escaper->escapeHtml(__('No results found.')) ?></p>
                        </template>
                    </div>
                    <?php if ($col2) : ?>
                </div>
            <?php endif; ?>
                <div class="py-4 px-6 w-full order-2 col-span-12">
                    <hr class="">
                    <div class="flex items-center justify-center">
                        <a x-bind:href="numberResultsUrl">
                            <p class="text-gray-900 transition duration-300 hover:text-gray-500 font-bold text-base lg:text-lg mt-4" x-html="numberResults"></p>
                        </a>
                    </div>
                </div>
            </div>
        </template>
        <template x-if="noResults">
            <div>
                <p class="text-lg leading-normal transition appearance-none text-grey-800 lg:text-xl" x-html="noResultsText"></p>
            </div>
        </template>
    </div>
</div>
<style>
    i {
        margin: 5px;
    }
</style>
<script>
    function initMirasvitSearch() {
        return {
            //initialize Variables
            hotSearch: false,
            searchResults: false,
            noResults: false,
            isLoading: false,
            isOpen: false,
            php_config: <?= json_encode($config); ?>,
            searchItems: [],
            searchCategories: [],
            searchPages: [],
            xhttp: false,
            noResultsText: '',
            numberResults: '',
            numberResultsUrl: '',
            searchItemsTotal: '',
            searchCategoriesTotal: '',
            searchPagesTotal: '',

            searchMap: {
                'magento_cms_page': 'Pages',
                'magento_catalog_category': 'Categories',
                'magento_catalog_product': 'Items'
            },

            hotSearchClickEvent: function(ev) {
                var hotSearchClick = event.currentTarget.innerText;
                document.getElementById("search").value = hotSearchClick;
                this.doSearch(hotSearchClick);
            },
            openSearch: function() {
                this.isOpen = true;
                searchValue = document.getElementById("search").value.length;
                if (searchValue >= this.php_config.minSearchLength) {
                    this.hideHotSearch();
                } else {
                    this.showHotSearch();
                    this.hideSearchResults();
                }
            },
            startSearch: function(e) {
                if (e) {
                    this.isOpen = true;
                }
            },
            closeSearch: function() {
                this.isOpen = false;
            },
            showHotSearch: function() {
                this.hotSearch = true;
            },
            hideHotSearch: function() {
                this.hotSearch = false;
            },
            showSearchResults: function() {
                this.searchResults = true;
            },
            hideSearchResults: function() {
                this.searchResults = false;
            },
            showNoResults: function() {
                this.noResults = true;
            },
            hideNoResults: function() {
                this.noResults = false;
            },
            setNoResultsText(text) {
                if (!text) {
                    return;
                }

                this.noResultsText = text;
            },
            setNumberResults(text) {
                this.numberResults = text;
            },
            setNumberResultsUrl(text) {
                this.numberResultsUrl = text;
            },
            resetSearchData: function() {
                // Reinitialize Variables to avoid wrong search results.
                this.searchPages = [];
                this.searchPagesTotal = 0;
                this.searchCategories = [];
                this.searchCategoriesTotal = 0;
                this.searchItems = [];
                this.searchItemsTotal = 0;
            },

            doSearch: function(query) {
                var self = this;
                // Min search length
                if (query.length < this.php_config.minSearchLength) {
                    this.showHotSearch();
                    this.isLoading = false;
                    this.hideSearchResults();
                    return;
                } else {
                    this.hideHotSearch();
                    this.isLoading = true;
                    this.showSearchResults();
                }

                // AJAX for searchautocomplete/ajax/suggest/
                if (this.xhttp) {
                    try {
                        this.xhttp.abort();
                    } catch {

                    }
                }
                this.xhttp = new XMLHttpRequest();
                var xhttp = this.xhttp;

                var queryEncoded = encodeURIComponent(query);
                var url = this.php_config.url.replace(/\/$/, "") + "/?q=" + queryEncoded + "&store_id=" + this.php_config.storeId + "&cat=false";

                xhttp.open("GET", url, true);
                xhttp.setRequestHeader("Content-Type", "application/json");

                xhttp.onreadystatechange = function() {
                    if (this.readyState == 4 && this.status == 200) {
                        // Response from ajax call in JSON.
                        var response = JSON.parse(this.responseText);

                        self.resetSearchData();

                        // Product Search Results
                        for (index in response.indexes) {

                            if (response.indexes[index].items.length > 0) {
                                var res = response.indexes[index];
                                var identifier = res.identifier;
                                var map = null;

                                if (self.searchMap[res.identifier]) {
                                    map = self.searchMap[res.identifier];
                                    self['search' + map] = res.items;
                                    self['search' + map + 'Total'] = res.totalItems;
                                }
                            }
                        }

                        self.isLoading = false;
                        self.hideNoResults();
                        self.setNumberResults(response.textAll);
                        self.setNumberResultsUrl(response.urlAll);

                        if (response.noResults) {
                            self.setNoResultsText(response.textEmpty);
                            self.hideSearchResults();
                            self.showNoResults();
                        }
                    }
                };
                xhttp.send();
            }
        }
    }
</script>
