<?php
$product = $block->getProduct();
$finalPrice = 0;
if ($product) {
    $finalPrice = $product->getFinalPrice();
}
?>
<div id="review-script">
    <!-- Placement v2 -->
    <klarna-placement
        data-key="credit-promotion-badge"
        data-locale="en-US"
        data-purchase-amount="<?= $finalPrice ?>"
    ></klarna-placement>
    <!-- end Placement -->
</div>
<script>
    (function () {
        const script = document.createElement('script')
        script.src = 'https://na-library.klarnaservices.com/lib.js';
        script.async = '';
        script.setAttribute('data-client-id', '604fbcf0-66da-5528-8cc5-82739a2766a9');
        document.getElementById('review-script').prepend(script);
    })();
</script>