<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Details $block */
/** @var Escaper $escaper */

use Magento\Catalog\Block\Product\View\Details;
use Magento\Framework\Escaper;

$titleRenderer = $block->getChildBlock('product.section.title.renderer');
$defaultTitleTemplate = $titleRenderer->getTemplate();

?>

<div class="p-0 mx-0 mt-8 mb-6 leading-6 text-center text-stone-500">
    <section x-data="{ selected: 'description' }">
        <nav role="tablist" id="tabs-tab">
            <div class="nav nav-tabs flex flex-col md:flex-row flex-wrap list-none justify-center pl-0">
                <?php
                foreach ($block->getGroupSortedChildNames('detailed_info', '') as $sectionName) {
                    $sectionBlock  = $block->getLayout()->getBlock($sectionName);
                    $sectionHtml   = (string) $sectionBlock->toHtml();
                    $titleTemplate = $sectionBlock->getData('title_template') ?? $defaultTitleTemplate;

                    if (empty(trim($sectionHtml))) {
                        continue;
                    }
                    $id = $sectionBlock->getNameInLayout();
                    ?>
                    <div class="inline-flex" :class="{ 'text-primary border-b-2 border-primary': selected === '<?= $id ?>' }">
                        <a class="block p-6 text-3xl font-normal leading-none text-center bg-white
                                hover:bg-white hover:pb-6" href="#description" x-on:click="selected = '<?= $id ?>'" role="tab">
                            <?= $escaper->escapeHtmlAttr($id) ?>
                        </a>
                    </div>
                    <div id="<?= $escaper->escapeHtmlAttr($id) ?>" x-show="selected === '<?= $sectionName ?>'" x-cloak>
                        <!-- <?=
                        $titleRenderer->setTemplate($titleTemplate)
                            ->assign('sectionBlock', $sectionBlock)
                            ->toHtml()
                        ?> -->
                        <div class="block float-none clear-both px-4 pt-2 pb-8 mx-0 mt-0 mb-1 leading-6 text-left
bg-white rounded border border-solid box-border border-neutral-200
text-stone-500">
                            <?= /** @noEscape  */ $sectionHtml ?>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </nav>

    </section>
</div>

