<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Details $block */
/** @var Escaper $escaper */

use Magento\Catalog\Block\Product\View\Details;
use Magento\Framework\Escaper;

$titleRenderer = $block->getChildBlock('product.section.title.renderer');
$defaultTitleTemplate = $titleRenderer->getTemplate();

?>

<div class="p-0 mx-0 mt-8 mb-6 leading-6 text-center text-stone-500">
    <section x-data="{ selected: 'description' }">
            <nav role="tablist" id="tabs-tab">
                <ul class="nav nav-tabs flex flex-row flex-wrap list-none md:justify-center pl-0">
                    <li :class="{ 'text-primary border-b-2 border-primary': selected === 'description' }">
                        <a class="block p-3 lg:p-6 md:text-2xl lg:text-3xl font-normal leading-none text-center
hover:bg-white hover:pb-6
hover:text-orange-500 focus:bg-white focus:pb-6 focus:text-orange-500
" href="#description" x-on:click="selected = 'description'" role="tab">Description</a>
                    </li>
                    <li :class="{ 'text-primary border-b-2 border-primary': selected === 'review.tab' }">
                        <a class="block p-3 lg:p-6 md:text-2xl lg:text-3xl font-normal leading-none text-center
                        hover:bg-white hover:pb-6
                        hover:text-orange-500 focus:bg-white focus:pb-6 focus:text-orange-500
                        " href="#review.tab" x-on:click="selected = 'review.tab'" role="tab">Review</a>
                    </li>
                    <li :class="{ 'text-primary border-b-2 border-primary': selected === 'payment.tab' }">
                        <a class="block p-3 lg:p-6 md:text-2xl lg:text-3xl font-normal leading-none text-center
                        hover:bg-white hover:pb-6
                        hover:text-orange-500 focus:bg-white focus:pb-6 focus:text-orange-500
                        " href="#payment.tab" x-on:click="selected = 'payment.tab'" role="tab">Payment</a></li>
                    <li :class="{ 'text-primary border-b-2 border-primary': selected === 'shipping.tab' }">
                        <a class="block p-3 lg:p-6 md:text-2xl lg:text-3xl font-normal leading-none text-center
hover:bg-white hover:pb-6
hover:text-orange-500 focus:bg-white focus:pb-6 focus:text-orange-500
" href="#shipping.tab" x-on:click="selected = 'shipping.tab'" role="tab">Shipping</a></li>
                    <li :class="{ 'text-primary border-b-2 border-primary': selected === 'whychooseus.tab' }"><a class="block p-3 lg:p-6 md:text-2xl lg:text-3xl font-normal leading-none text-center
hover:bg-white hover:pb-6
hover:text-orange-500 focus:bg-white focus:pb-6 focus:text-orange-500
" href="#whychooseus.tab" x-on:click="selected = 'whychooseus.tab'" role="tab">Why Choose Us</a></li>
                </ul>
            </nav>
            <div class="grid">
<?php
foreach ($block->getGroupSortedChildNames('detailed_info', '') as $sectionName) {
    $sectionBlock  = $block->getLayout()->getBlock($sectionName);
    $sectionHtml   = (string) $sectionBlock->toHtml();
    $titleTemplate = $sectionBlock->getData('title_template') ?? $defaultTitleTemplate;

    if (empty(trim($sectionHtml))) {
        continue;
    }
    ?>
                <div id="<?= $escaper->escapeHtmlAttr($sectionBlock->getNameInLayout()) ?>" x-show="selected === '<?= $sectionName ?>'" x-cloak>
        <!-- <?=
            $titleRenderer->setTemplate($titleTemplate)
                          ->assign('sectionBlock', $sectionBlock)
                          ->toHtml()
        ?> -->
        <div class="block float-none clear-both px-4 pt-2 pb-8 mx-0 mt-0 mb-1 leading-6 text-left
bg-white rounded border border-solid box-border border-neutral-200
text-stone-500">
            <?= /** @noEscape  */ $sectionHtml ?>
        </div>
                </div>
<?php } ?>
            </div>
    </section>
</div>

