<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Hyva_BssMegaMenu
 * @author     Extension Team
 * @copyright  Copyright (c) 2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Navigation;
use Bss\MegaMenu\Block\Html\Menu;
use Magento\Framework\Escaper;

/** @var Menu $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$block->setData('cache_tags', $viewModelNavigation->getIdentities());
$helper = $block->getHelperData();
$megaMenuItems = $block->getMegaMenuData();
?>
<div x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
     class="z-20 order-2 sm:order-1 lg:order-2 navigation lg:hidden"
>
    <!-- mobile -->
    <div @load.window="setActiveMenu($el)"
         class="bg-container-lighter"
         :class="{'h-screen overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full' : open}"
         @toggle-mobile-menu.window="open = !open"
         @keydown.window.escape="open=false"
    >
        <div class="flex items-baseline justify-between menu-icon">
            <div class="flex justify-end w-full">
                <a @click="$dispatch('toggle-mobile-menu')"
                   class="flex items-center justify-center cursor-pointer"
                   :class="{ 'ml-auto': open }">
                    <svg class="hidden w-16 h-16 p-4 fill-current"
                         :class="{ 'hidden' : !open, 'block': open }"
                         xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                         viewBox="0 0 20 20">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                              d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0
                          1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828
                          4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z">
                        </path>
                    </svg>
                    <svg class="block w-12 h-12 p-3 fill-current"
                         :class="{ 'hidden' : open, 'block': !open }"
                         xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                         viewBox="0 0 20 20">
                        <path
                            d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z">
                        </path>
                    </svg>
                </a>
            </div>
        </div>

        <nav
            class="hidden w-full duration-150 ease-in-out transform border-t transition-display border-container"
            :class="{ 'hidden' : !open }"
        >
            <?php if ($helper->getConfig('enable_home') == 1): ?>
            <div class="level-0">
                <span class="flex items-center transition-transform duration-150 ease-in-out transform"
                      :class="{'-translate-x-full': mobilePanelActiveId}">
                    <a class="flex items-center w-full px-8 py-4 border-b cursor-pointer bg-container-lighter border-container hover:bg-container-darker hover:underline level-0"
                       href="<?= $escaper->escapeUrl($block->getBaseUrl()) ?>"
                       title="<?= $block->escapeHtml(__("Home")) ?>">
                        <?= $block->escapeHtml(__("Home")) ?>
                    </a>
                </span>
            </div>
            <?php endif; ?>

            <?php $level = 0 ?>
            <?php foreach ($megaMenuItems as $item): ?>
                <div class="level-<?= /** @noEscape */ $level ?>">
                    <span
                        class="flex items-center transition-transform duration-150 ease-in-out transform"
                        :class="{'-translate-x-full': mobilePanelActiveId}"
                    >
                        <a class="flex items-center w-full px-8 py-4 border-b cursor-pointer bg-container-lighter border-container hover:bg-container-darker level-0"
                           href="<?= $escaper->escapeUrl($item['url']) ?>"
                           title="<?= $escaper->escapeHtmlAttr($item['name']) ?>">
                            <span class="mr-2 hover:underline category-name"><?= $escaper->escapeHtml($item['name']) ?></span>
                            <?= /** @noEscape */ $item['label_html'] ?>
                        </a>
                        <?php if (!empty($item['children']) || (isset($item['block_html']) && !empty($item['block_html']))): ?>
                            <a class="absolute right-0 flex w-8 h-8 mr-8 border rounded cursor-pointer
                        bg-container-lighter border-container hover:bg-container hover:border-container"
                               @click="handleNextMenu('<?= $item['id'] ?>')"
                            >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" height="24" width="24"
                             stroke="currentColor"
                             class="w-full h-full p-1"
                        >
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                        </svg>
                    </a>
                        <?php endif; ?>
                    </span>
                    <?php if (!empty($item['children']) || (isset($item['block_html']) && !empty($item['block_html']))): ?>
                        <div
                            class="absolute top-0 right-0 z-10 w-full h-auto transition-transform duration-200 ease-in-out
                                transform bg-container-lighter"
                            :class="{
                                'translate-x-full': !mobilePanelActiveId || !activeIds.includes('<?= $item['id'] ?>'),
                                '-translate-x-full': mobilePanelActiveId !== '<?= $item['id'] ?>',
                            }"
                        >
                            <a class="flex items-center px-8 py-4 border-b cursor-pointer bg-container border-container"
                               @click="mobilePanelActiveId = null, removeActiveId('<?= $item['id'] ?>')"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" height="24"
                                     width="24"
                                     stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                          d="M15 19l-7-7 7-7"/>
                                </svg>
                                <span class="ml-4"><?= $escaper->escapeHtml($item['name']) ?></span>
                            </a>

                            <?php if (isset($item['block_html']['top'])) : ?>
                                <?= /** @noEscape */ $item['block_html']['top'] ?>
                            <?php endif; ?>
                            <?php if (isset($item['block_html']['left'])) : ?>
                                <?= /** @noEscape */ $item['block_html']['left'] ?>
                            <?php endif; ?>

                            <?php if (!(isset($item['block_html']) && !empty($item['block_html']))): ?>
                                <a href="<?= $escaper->escapeUrl($item['url']) ?>"
                                   title="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                                   class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                            bg-container-lighter border-container hover:bg-container-darker hover:underline"
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                         viewBox="0 0 24 24" height="24"
                                         width="24"></svg>
                                    <span class="ml-3"><?= $escaper->escapeHtml(__('View All')) ?></span>
                                </a>
                            <?php endif; ?>

                            <?php if (empty($item['children']) && isset($item['block_html']['center'])): ?>
                                <?= /** @noEscape */ $item['block_html']['center'] ?>
                            <?php endif; ?>

                            <?php foreach ($item['children'] as $childItem): ?>
                                <?= /** @noEscape */ $block->renderMenuChildrenMobile($childItem, 1, $item['id']) ?>
                            <?php endforeach; ?>

                            <?php if (isset($item['block_html']['right'])) : ?>
                                <?= /** @noEscape */ $item['block_html']['right'] ?>
                            <?php endif; ?>
                            <?php if (isset($item['block_html']['bottom'])) : ?>
                                <?= /** @noEscape */ $item['block_html']['bottom'] ?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>

        </nav>
    </div>
</div>

<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActive: {},
            mobilePanelActiveId: null,
            hoverPanelActiveId: null,
            activeIds: [],
            open: false,
            openLevel: 0,
            removeActiveId (id) {
                this.activeIds = this.activeIds.filter(currentId => currentId !== id);
            },
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.querySelector('span.category-name') &&
                    item.querySelector('span.category-name').classList.add('underline');
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').querySelector('a.level-0 span.category-name') &&
                    item.closest('div.level-0').querySelector('a.level-0 span.category-name').classList.add('underline');
                });
            },
            handleNextMenu (itemId, parentId) {
                // this.mobilePanelActive[itemId] = true;
                //
                // if (this.mobilePanelActive.hasOwnProperty(parentId)) {
                //     this.mobilePanelActive[parentId] = false;
                // }
                this.mobilePanelActiveId = itemId;
                this.activeIds.push(itemId);
            },
            display (itemId) {
                return this.mobilePanelActive.hasOwnProperty(itemId) && this.mobilePanelActive[itemId] === true;
            }
        }
    }
</script>
