<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');
$buttonImg = $block->getViewFileUrl('Magento_Newsletter::image/paper-plane.svg');
?>
<div class="flex-grow-0 pl-3 flex-shrink-0 mb-0 max-w-full leading-6 basis-full">
    <h4 class="inline-block overflow-hidden text-primary font-bold text-center align-middle tracking-wider" style="text-decoration: none; speak: none; right: 10px; top: -7px;">
        SUBSCRIBE TO NEWSLETTER
    </h4>
    <div class="pr-4">
        <p class="text-white py-4">Subscribe to our Newsletter and get bonuses for the next purchase.</p>
        <form class="form subscribe"
              action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              x-data="initNewsletterForm()"
              @submit.prevent="submitForm()"
              id="newsletter-validate-detail">
            <div class="flex justify-center md:justify-start">
                <input name="email"
                    type="email"
                    required
                    id="newsletter-subscribe"
                    class="inline-flex w-full"
                    placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your email address')) ?>">
                <?= $block->getBlockHtml('formkey') ?>
                <button class="rounded-none action subscribe primary inline-flex flex-shrink-0 ml-auto xl:mt-0 btn btn-primary" title="Subscribe" type="submit" aria-label="Subscribe" style="height: 45px;">
                    <img src="<?= $escaper->escapeUrl($buttonImg);?>" alt="Send">
                </button>
                <!-- <button class="inline-flex flex-shrink-0 ml-auto xl:mt-0 btn btn-primary">
                    <?= $escaper->escapeHtml(__('Subscribe')) ?>
                </button> -->
                <?= $recaptcha ? $recaptcha->getInputHtml('newsletter') : '' ?>
            </div>
            <div>
                <template x-if="displayErrorMessage">
                    <p class="flex items-center text-red">
                        <span class="inline-block w-8 h-8 mr-3">
                            <?= $heroicons->exclamationCircleHtml(); ?>
                        </span>
                        <template x-for="errorMessage in errorMessages">
                            <span x-html="errorMessage"></span>
                        </template>
                    </p>
                </template>
            </div>
        </form>
        <div class="w-full">
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml('newsletter') : '' ?>
        </div>
        <script>
            function initNewsletterForm() {
                return {
                    errors: 0,
                    hasCaptchaToken: 0,
                    displayErrorMessage: false,
                    errorMessages: [],
                    setErrorMessages(messages) {
                        this.errorMessages = [messages]
                        this.displayErrorMessage = this.errorMessages.length
                    },
                    submitForm() {
                        // Do not rename $form, the variable is expected to be declared in the recaptcha output
                        const $form = document.querySelector('#newsletter-validate-detail');
                        <?= $recaptcha ? $recaptcha->getValidationJsHtml('newsletter') : '' ?>
    
                        if (this.errors === 0) {
                            $form.submit();
                        }
                    }
                }
            }
        </script>
    </div>
</div>
